const primitive = {
  color: {
    green50: '#E8F3EC',
    green500: '#0F5E46',
    green600: '#0C5039',
    green700: '#0B4732',
    forest900: '#16231F',
    stone0: '#FFFFFF',
    stone50: '#F7F3EA',
    stone100: '#ECE8E0',
    stone150: '#DED8CD',
    stone200: '#DAD4C9',
    stone250: '#E5DFD5',
    stone300: '#ECE7DE',
    stone500: '#7A817C',
    stone600: '#66716B',
    stone650: '#52635D',
    stone700: '#31433C',
    stone800: '#16231F',
    ink900: '#0C1311',
    amber600: '#8A4B00',
    amber50: '#FBEBD0',
    coral600: '#B8432F',
    coral50: '#FFECE6',
    blue600: '#17324D',
    blue50: '#EAF1F8',
  },
  space: { 0.5: 2, 1: 4, 2: 8, 3: 12, 4: 16, 5: 20, 6: 24, 7: 28, 8: 32, 10: 40, 12: 48 },
  radius: { small: 8, control: 14, card: 16, sheet: 24, pill: 999, tab: 22 },
  motion: { fast: 150, standard: 220, emphasis: 320 },
} as const;

const semantic = {
  color: {
    backgroundCanvas: primitive.color.stone50,
    backgroundSurface: primitive.color.stone0,
    backgroundSubtle: primitive.color.stone100,
    textPrimary: primitive.color.forest900,
    textSecondary: primitive.color.stone650,
    textMuted: primitive.color.stone500,
    textOnPrimary: primitive.color.stone0,
    borderDefault: primitive.color.stone300,
    borderStrong: primitive.color.stone150,
    borderTabs: primitive.color.stone250,
    borderFilter: primitive.color.stone200,
    actionPrimary: primitive.color.green500,
    actionPrimaryPressed: primitive.color.green700,
    actionSecondaryBackground: primitive.color.stone100,
    actionInverseBackground: primitive.color.forest900,
    trustSurface: primitive.color.green50,
    trustText: primitive.color.green500,
    warningSurface: primitive.color.amber50,
    warningText: primitive.color.amber600,
    dangerSurface: primitive.color.coral50,
    dangerText: primitive.color.coral600,
    infoSurface: primitive.color.blue50,
    infoText: primitive.color.blue600,
    reasonSurface: primitive.color.blue50,
    reasonText: primitive.color.blue600,
    focus: primitive.color.green500,
    tabBarBackground: primitive.color.stone0,
    tabActive: primitive.color.green500,
    tabInactive: primitive.color.stone500,
  },
} as const;

export const tokens = {
  primitive,
  semantic,
  typography: {
    family: 'Manrope',
    display: { fontSize: 32, lineHeight: 38, fontWeight: '700', letterSpacing: -0.6 },
    screenTitle: { fontSize: 28, lineHeight: 34, fontWeight: '700', letterSpacing: -1 },
    title1: { fontSize: 26, lineHeight: 33, fontWeight: '700', letterSpacing: -0.9 },
    title2: { fontSize: 22, lineHeight: 28, fontWeight: '700', letterSpacing: -0.4 },
    title3: { fontSize: 19, lineHeight: 25, fontWeight: '700', letterSpacing: -0.4 },
    title4: { fontSize: 16, lineHeight: 22, fontWeight: '700' },
    bodyLarge: { fontSize: 16, lineHeight: 23, fontWeight: '400' },
    body: { fontSize: 15, lineHeight: 22, fontWeight: '400' },
    bodyStrong: { fontSize: 15, lineHeight: 22, fontWeight: '600' },
    label: { fontSize: 13, lineHeight: 18, fontWeight: '600' },
    labelStrong: { fontSize: 12, lineHeight: 17, fontWeight: '700' },
    caption: { fontSize: 12, lineHeight: 17, fontWeight: '500' },
    micro: { fontSize: 11, lineHeight: 15, fontWeight: '700' },
    nano: { fontSize: 10, lineHeight: 14, fontWeight: '600' },
    tabLabel: { fontSize: 10, lineHeight: 13, fontWeight: '700' },
  },
  component: {
    button: {
      height: 48,
      radius: primitive.radius.control,
      primary: {
        background: semantic.color.actionPrimary,
        foreground: primitive.color.stone0,
      },
      secondary: {
        background: 'transparent',
        foreground: semantic.color.textPrimary,
      },
    },
    input: { minHeight: 48, radius: primitive.radius.control },
    intentCard: {
      background: semantic.color.backgroundSurface,
      border: semantic.color.borderDefault,
      radius: primitive.radius.card,
      padding: primitive.space[4],
    },
    tabBar: {
      height: 84,
      background: semantic.color.tabBarBackground,
      borderColor: semantic.color.borderTabs,
    },
    filterChip: {
      height: 38,
      radius: primitive.radius.pill,
    },
  },
} as const;

export type NearcastTokens = typeof tokens;
